application: grmblechat
version: 1
runtime: python
api_version: 1

handlers:

- url: /api/room/[^/]+/[^/]+/github/
  script: github.py

- url: /api/.*
  script: api.py

- url: /account/[^/]*
  script: account.py
  login: required

- url: /room/[^/]*
  script: room.py
  login: required

- url: /room/[^/]+/admin
  script: room.py
  login: required

- url: /room/[^/]+/leave
  script: room.py
  login: required

- url: /tasks/.*
  script: tasks.py
  login: admin

- url: /css
  static_dir: css 
  expiration: 1d

- url: /js
  static_dir: js
  expiration: 1d

- url: /images
  static_dir: images
  expiration: 1d

- url: /sounds
  static_dir: sounds
  expiration: 1d

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: .*
  script: main.py
